services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mariadb:
    image: mariadb:latest
    container_name: mariadb_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: python_app
    depends_on:
      - postgres
      - mariadb
    volumes:
      - .:/app
    stdin_open: true  # Keep container open for interaction
    tty: true         # Allocate a pseudo-TTY

volumes:
  pgdata:
  mariadbdata:
